version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: restful_sql
      POSTGRES_USER: restful
      POSTGRES_PASSWORD: restful
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d
